export const FETCH_SECTIONS = 'CATALOG/FETCH_SECTIONS'
export const FETCH_SUB_SECTIONS = 'CATALOG/FETCH_SUB_SECTIONS'
export const FETCH_BRANDS = 'CATALOG/ADD_BRANDS'
export const FETCH_SPORT_TYPES = 'CATALOG/ADD_SPORT_TYPES'
export const FETCH_ALL_SIZES = 'CATALOG/FETCH_ALL_SIZES'

export const CONCAT_PRODUCTS_PREVIEW_INFO = 'CATALOG/PRODUCTS/ADD_PRODUCTS_PREVIEW_INFO'
export const UPDATE_PRODUCTS_PREVIEW_INFO = 'CATALOG/PRODUCTS/UPDATE_PRODUCTS_PREVIEW_INFO'
export const SORT_PRODUCTS_PREVIEW_INFO = 'CATALOG/PRODUCTS/SORT_PRODUCTS_PREVIEW_INFO'

export const UPDATE_PRODUCTS_PREVIEW_COUNT = 'CATALOG/PRODUCTS/UPDATE_PRODUCTS_PREVIEW_COUNT'

export const ADD_FULL_INFO_ABOUT_CURRENT_PRODUCT = 'CATALOG/PRODUCTS/CURRENT/GET_FULL_INFO_ABOUT_CURRENT_PRODUCT'
export const DELETE_FULL_INFO_ABOUT_CURRENT_PRODUCT = 'CATALOG/PRODUCTS/CURRENT/DELETE_FULL_INFO_ABOUT_CURRENT_PRODUCT'

export const FETCH_USER_INFO = 'USER/FETCH_USER_INFO'
export const UPDATE_USER_INFO = 'USER/UPDATE_USER_INFO'
export const UPDATE_USER_ADDRESS = 'USER/UPDATE_USER_ADDRESS'
export const CLEAR_USER_INFO = 'USER/CLEAR_USER_INFO'

export const ADD_ALL_PREVIEWS_BASKET = 'BASKET/ADD_ALL_PREVIEWS_BASKET'
export const ADD_ORDER_POSITION = 'BASKET/ADD_ORDER_POSITION'
export const DELETE_ORDER_POSITION = 'BASKET/DELETE_ORDER_POSITION'