export const FETCH_SECTIONS = 'CATALOG/FETCH_SECTIONS'
export const FETCH_SUB_SECTIONS = 'CATALOG/FETCH_SUB_SECTIONS'
export const ADD_BRANDS = 'CATALOG/ADD_BRANDS'
export const ADD_SPORT_TYPES = 'CATALOG/ADD_SPORT_TYPES'